version: '3.9'

services:
  routing:
    build: .
    container_name: arrival_times_service
    ports:
      - "8001:8000"
    volumes:
      - .:/code
    command: python manage.py runserver 0.0.0.0:8000