apiVersion: apps/v1
kind: Deployment
metadata:
  name: routing-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: routing
  template:
    metadata:
      labels:
        app: routing
    spec:
      containers:
        - name: routing
          image: routing_service-routing:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c", "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
