apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: routing-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: routing-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
